### ISSUE TITLE
Protocol Documetation

### ISSUE THREAD

**Issue by pjmolina** [Strumenta/MPSServer#3]
Hi @ftomassetti 
Very useful project!

Do you have pointers to documentation for this communication protocol you expose?
Or plans to add it to this project?

**Comment by ftomassetti** [comment]
Thank you!

No, there is zero documentation at the moment. The reason is that this is in a very early stage and things change quickly.

Basically there are two ways to communicate with the server:
* through HTTP to get lists of modules, models, and roots
* through WS to be notified of changes and to operate changes

We may want to have some of these operations being available through the two protocols.

At the moment one has to look at the code of MPSServer or WebEditKit to figure out the protocol. Or ask :D 

But later, if this proves to be useful and doable, and the project survives the alpha stage, for sure we will document the protocol

**Comment by ftomassetti** [comment]
A bit late but we did it. Now under documentation the http and the ws protocols are described
